name: web-automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  UI-web-tests:
    name: Run UI Web Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 

      - name: Cache Gradle dependencies
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Run Tests
        run: ./gradlew clean test  # Menjalankan perintah Gradle untuk membangun dan menjalankan pengujian

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-web-test-report
          path: build/reports/tests/test  # Path default untuk laporan pengujian Gradle

  
