name: Web UI Automation Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-automation-test:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Download Repositori
    - uses: actions/checkout@v4
    
    # Setup Java JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

   # Install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.2.3

   # Setup gradlew
    - name: Setup Gradlew
      run: chmod +x gradlew

    # Execute gradlew for running cucumber test
    - name: Execute test
      run: ./gradlew cucumber

    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.3
      if: always()
      with:
        name: Cucumber Report
        path: reports

    # Deploy to GitHub Pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
      
