name: UI Web Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Install Chrome
    - name: Set up Chrome 130
      uses: browser-actions/setup-chrome@v1.7.2
      with:
        version: '130'

    # Step 4: Make Gradle Wrapper executable
    - name: Make Gradle Wrapper Executable
      run: chmod +x ./gradlew

    # Step 5: Execute Tests
    - name: Run Tests
      run: ./gradlew WebRun

    - name: Archive test result
      uses: actions/upload-artifact@v4
      if: always()
      with:
       name: cucumber reports
       path: reports/web/index.html
 
  
